/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.event.ActionListener;
import negocio.IEquipoNegocio;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import negocio.IBloqueoNegocio;
import negocio.IUsoNegocio;
import utilerias.ButtonEditor;
import utilerias.ButtonRenderer;

/**
 *
 * @author hp
 */
public class FrmAdministracionListaComputadoras extends javax.swing.JFrame {

    private IUsoNegocio usoNegocio;
    private IBloqueoNegocio bloqueoNegocio;
    private IEquipoNegocio equipoNegocio;
    private Timer temporizadorActualizacion;
    private IUsoNegocio conexionNegocio;
    private String textoBusquedaActual = "";
    private String laboratorioActual = "Laboratorio";
    private int paginaActual = 1;
    private final int LIMITE_POR_PAGINA = 5;
    private int totalPaginas = 1;
    private List<dto.ListarEquipoDTO> listaActual;

    /**
     * Creates new form FrmAdministracionListaComputadoras
     */
    public FrmAdministracionListaComputadoras(IUsoNegocio conexionNegocio, negocio.IEquipoNegocio equipoNegocio, IBloqueoNegocio bloqueoNegocio) {
        this.conexionNegocio = conexionNegocio;
        this.equipoNegocio = equipoNegocio;
        this.bloqueoNegocio = bloqueoNegocio;
        initComponents();

        cargarComboBoxLaboratorios();

        configurarTabla();
        cargarTablaEquipos();
        iniciarActualizacionAutomatica();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBloquados = new javax.swing.JButton();
        btnUso = new javax.swing.JButton();
        btnApartados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LblTituloTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TlbBloqueados = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        TxtBuscador = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSiguinte = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnListas = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 224, 218));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 609));

        btnBloquados.setText("Bloqueados");
        btnBloquados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquadosActionPerformed(evt);
            }
        });

        btnUso.setText("Uso");
        btnUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsoActionPerformed(evt);
            }
        });

        btnApartados.setText("Apartados");
        btnApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartadosActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(227, 224, 218));

        LblTituloTabla.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblTituloTabla.setText("Lista de computadoras");

        TlbBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero Computadora", "Direccion IP", "Estado", "Acciones de apartado"
            }
        ));
        jScrollPane1.setViewportView(TlbBloqueados);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        TxtBuscador.setText("Buscar...");
        TxtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscadorActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laboratorio", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTituloTabla)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(TxtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSiguinte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguinte.setText("siguiente");
        btnSiguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguinteActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras.setText("atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnListas.setText("Listas");
        btnListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListasActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblTitulo.setText("PANEL DE ADMINISTRACION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBloquados)
                .addGap(40, 40, 40)
                .addComponent(btnUso, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnApartados, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnListas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnAtras)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguinte))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBloquados)
                    .addComponent(btnUso)
                    .addComponent(btnApartados)
                    .addComponent(btnListas))
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguinte)
                    .addComponent(btnAtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloquadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquadosActionPerformed
        FrmAdministracionBloqueados ventana = new FrmAdministracionBloqueados(this.conexionNegocio, this.equipoNegocio, this.bloqueoNegocio);

        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBloquadosActionPerformed

    private void btnUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsoActionPerformed
        FrmAdministracionUsos ventana = new FrmAdministracionUsos(this.conexionNegocio, this.equipoNegocio);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsoActionPerformed

    private void btnApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartadosActionPerformed
        FrmAdministracionUsos ventana = new FrmAdministracionUsos(this.usoNegocio, this.equipoNegocio);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnApartadosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        textoBusquedaActual = TxtBuscador.getText().trim();

        if (textoBusquedaActual.equals("Buscar...") || textoBusquedaActual.isEmpty()) {
            textoBusquedaActual = "";
        }

        if (jComboBox1.getSelectedItem() != null) {
            laboratorioActual = jComboBox1.getSelectedItem().toString();
        }

        paginaActual = 1;
        cargarTablaEquipos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TxtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscadorActionPerformed

    private void btnSiguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguinteActionPerformed
        // TODO add your handling code here:
        if (paginaActual < totalPaginas) {
            paginaActual++;
            cargarTablaEquipos();
        }
    }//GEN-LAST:event_btnSiguinteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1) {
            paginaActual--;
            cargarTablaEquipos();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnListasActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() != null) {
            laboratorioActual = jComboBox1.getSelectedItem().toString();
            paginaActual = 1;
            cargarTablaEquipos();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarTabla() {
        TlbBloqueados.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());

        TlbBloqueados.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JCheckBox(), () -> {
            accionBotonTabla();
        }));
    }

    private void cargarTablaEquipos() {
        DefaultTableModel modeloTabla = (DefaultTableModel) TlbBloqueados.getModel();
        modeloTabla.setRowCount(0);

        try {
            totalPaginas = equipoNegocio.obtenerTotalPaginas(laboratorioActual, textoBusquedaActual, LIMITE_POR_PAGINA);
            if (totalPaginas == 0) {
                totalPaginas = 1;
            }

            listaActual = equipoNegocio.buscarEquiposPaginados(laboratorioActual, textoBusquedaActual, LIMITE_POR_PAGINA, paginaActual);

            for (dto.ListarEquipoDTO equipo : listaActual) {

                String textoBoton = equipo.getEstado().equalsIgnoreCase("Disponible") ? "Deshabilitar" : "Habilitar";

                Object[] filaNueva = {
                    equipo.getNumeroComputadora(),
                    equipo.getDireccionIP(),
                    equipo.getEstado(),
                    textoBoton
                };

                modeloTabla.addRow(filaNueva);
            }

            actualizarBotonesPaginacion();

        } catch (Exception e) {
            System.out.println("Aviso: " + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void accionBotonTabla() {
        Integer fila = (Integer) TlbBloqueados.getClientProperty("filaSeleccionada");
        cargarTablaEquipos();

        if (fila != null && fila >= 0 && fila < listaActual.size()) {

            dto.ListarEquipoDTO equipoSeleccionado = listaActual.get(fila);
            int idEquipo = equipoSeleccionado.getId();

            String nuevoEstado = equipoSeleccionado.getEstado().equalsIgnoreCase("Disponible") ? "Mantenimiento" : "Disponible";

            try {
                equipoNegocio.cambiarEstadoEquipo(idEquipo, nuevoEstado);

                JOptionPane.showMessageDialog(this, "El estado del equipo se actualizó a: " + nuevoEstado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTablaEquipos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargarTablaEquipos();

        }
    }

    private void cargarComboBoxLaboratorios() {
        try {
            jComboBox1.removeAllItems();

            List<String> laboratorios = equipoNegocio.obtenerNombresLaboratorios();

            for (String lab : laboratorios) {
                jComboBox1.addItem(lab);
            }

            if (jComboBox1.getItemCount() > 0) {
                jComboBox1.setSelectedIndex(0);
                laboratorioActual = jComboBox1.getSelectedItem().toString();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los laboratorios: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarBotonesPaginacion() {
        btnAtras.setEnabled(paginaActual > 1);
        btnSiguinte.setEnabled(paginaActual < totalPaginas);
    }

    private void iniciarActualizacionAutomatica() {
        int intervalo = 30000;
        temporizadorActualizacion = new Timer(intervalo, new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cargarTablaEquipos();

            }
        });

        temporizadorActualizacion.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTituloTabla;
    private javax.swing.JTable TlbBloqueados;
    private javax.swing.JTextField TxtBuscador;
    private javax.swing.JButton btnApartados;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBloquados;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListas;
    private javax.swing.JButton btnSiguinte;
    private javax.swing.JButton btnUso;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
