/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.BloquearAlumnoDTO;
import entidad.BloqueoEntidad;
import javax.swing.JOptionPane;
import negocio.IBloqueoNegocio;
import negocio.NegocioException;

/**
 *
 * @author USUARIO
 */
public class FrmBloqueoAlumno extends javax.swing.JFrame {
     private IBloqueoNegocio bloqueoNegocio;
     
    /**
     * Creates new form FrmBloqueoAlumno
     */
    public FrmBloqueoAlumno(IBloqueoNegocio bloqueoNegocio) {
        initComponents();
        this.bloqueoNegocio = bloqueoNegocio;
        System.out.println("Negocio recibido: " + bloqueoNegocio);
    }

    public FrmBloqueoAlumno() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblMotivo = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        LblID = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtMotivo = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnBloquear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LblMotivo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblMotivo.setText("Motivo:");

        LblTitulo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblTitulo.setText("Bloquear alumno");

        LblID.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblID.setText("Id Alumno:");

        TxtMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMotivoActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnBloquear.setBackground(new java.awt.Color(0, 102, 0));
        BtnBloquear.setText("Boquear");
        BtnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(BtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBloquear)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LblTitulo)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblID)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMotivo)
                    .addComponent(TxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnBloquear))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
         this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBloquearActionPerformed
        String motivo = TxtMotivo.getText().trim();
        registrarBloqueo(motivo);
    
    }//GEN-LAST:event_BtnBloquearActionPerformed

    private void TxtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMotivoActionPerformed
    
    private void registrarBloqueo(String motivo) {
        try {
            this.validacionesBloquearAlumno();
            BloquearAlumnoDTO nuevoAlumno = this.crearObjetoBloqueoDTO();
            
            BloqueoEntidad alumnoBloqueado = this.bloqueoNegocio.bloquear(nuevoAlumno);
            
            JOptionPane.showMessageDialog(this, "El alumno ha sido bloqueado.");
            
            this.dispose();
            
        } catch (NegocioException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             
        } catch (PresentacionException ex) {
              JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
     private BloquearAlumnoDTO crearObjetoBloqueoDTO() {
        String idTexto= TxtId.getText().trim();
        
         try {      
            validarCampo(idTexto, "el id es obligatorio");
       
        } catch (PresentacionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
         
        int idAlumno = Integer.parseInt(idTexto);
        return new BloquearAlumnoDTO(
                idAlumno, 
                TxtMotivo.getText().trim()  
            );
    }
     
     private void validarLongitud(String valor, int longitudMaxima, String nombreCampo)
            throws PresentacionException {

        if (valor.length() > longitudMaxima) {
            throw new PresentacionException(
                    nombreCampo + " no puede exceder los " + longitudMaxima + " caracteres");
        }
    }
    
    private void validarCampo(String valor, String mensaje) throws PresentacionException {
        if (valor == null || valor.trim().isEmpty()) {
            throw new PresentacionException(mensaje);
        } 
    }
    
    private void validarIdNumerico(String valor) throws PresentacionException {
        if(!valor.matches("\\d+")) {
            throw new PresentacionException("El id debe contener solo numeros.");
        }
    }

    private void validarLongitudes() throws PresentacionException {
        validarLongitud(TxtMotivo.getText(), 150, "El motivo excede la longitud permitida");
    }

    private void validarCamposVacios() throws PresentacionException {
        validarCampo(TxtId.getText(), "El id es obligatorio");
        validarIdNumerico(TxtId.getText().trim());
        validarCampo(TxtMotivo.getText(), "El motivo es obligatorio");
    }

    private void validacionesBloquearAlumno() throws PresentacionException {
        this.validarCamposVacios();
        this.validarLongitudes();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBloquear;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblMotivo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtMotivo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
