/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.IEquipoNegocio;

import dto.SoftwareDTO;
import entidad.AlumnoEntidad;
import negocio.IEquipoNegocio;
import java.util.List;
import java.util.ArrayList;
import negocio.AlumnoNegocio;
import negocio.EquipoNegocio;
import negocio.IAlumnoNegocio;
import negocio.IUsoNegocio;
import negocio.UsoNegocio;
import persistencia.AlumnoDAO;
import persistencia.ConexionBD;
import persistencia.EquipoDAO;
import persistencia.IAlumnoDAO;
import persistencia.IConexionBD;
import persistencia.IEquipoDAO;
import persistencia.IIpDAO;
import persistencia.IUsoDAO;
import persistencia.IpDAO;
import persistencia.UsoDAO;

/**
 *
 * @author USUARIO
 */
public class FrmListaSoftwaresEquipo extends javax.swing.JFrame {

    private IEquipoNegocio equipoNegocio;
    private int idEquipo;
    private int numeroEquipo;
    private List<SoftwareDTO> todosSoftwares;

    /**
     * Creates new form FrmListaSoftwaresEquipo
     */
    public FrmListaSoftwaresEquipo(IEquipoNegocio equipoNegocio,
            int idEquipo,
            int numeroEquipo) {
        this.equipoNegocio = equipoNegocio;
        this.idEquipo = idEquipo;
        this.numeroEquipo = numeroEquipo;

        // 2. ¡MUY IMPORTANTE! Creas la pantalla visual y todos sus elementos (botones, etiquetas)
        initComponents();

        // 3. Modificas el título para que muestre el número de equipo real
        this.LblTitulo.setText("Softwares Instalados en el equipo " + numeroEquipo + ":");

        // 4. Ahora sí, buscas y cargas los softwares en la etiqueta que ya existe
        cargarSoftwares();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblLista = new javax.swing.JLabel();
        TxtBuacador = new javax.swing.JTextField();
        BtnBuscar1 = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnContunuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFondo.setBackground(new java.awt.Color(204, 204, 204));

        LblTitulo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblTitulo.setText("Softwares Intalados en el equipo x:");

        LblLista.setText(" lista ");

        TxtBuacador.setText("Introduca un software a buacar...");
        TxtBuacador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuacadorActionPerformed(evt);
            }
        });

        BtnBuscar1.setText("Buscar");
        BtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscar1ActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar.setText("Cancelar apartado");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnContunuar.setBackground(new java.awt.Color(0, 102, 0));
        BtnContunuar.setText("Continuar apartado");
        BtnContunuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContunuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFondoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(LblLista, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFondoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(TxtBuacador, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(BtnCancelar)
                .addGap(29, 29, 29)
                .addComponent(BtnContunuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFondoLayout.createSequentialGroup()
                    .addContainerGap(462, Short.MAX_VALUE)
                    .addComponent(BtnBuscar1)
                    .addGap(55, 55, 55)))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblTitulo)
                .addGap(18, 18, 18)
                .addComponent(TxtBuacador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LblLista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnContunuar))
                .addGap(36, 36, 36))
            .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlFondoLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(BtnBuscar1)
                    .addContainerGap(297, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuacadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuacadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuacadorActionPerformed

    private void BtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscar1ActionPerformed
        // TODO add your handling code here:
        String filtro = TxtBuacador.getText().trim().toLowerCase();

        if (filtro.isEmpty() || filtro.equals("introduca un software a buacar...")) {
            mostrarSoftwares(todosSoftwares);
            return;
        }

        List<SoftwareDTO> filtrados = new ArrayList<>();
        for (SoftwareDTO sw : todosSoftwares) {
            if (sw.getNombre().toLowerCase().contains(filtro)) {
                filtrados.add(sw);
            }
        }
        mostrarSoftwares(filtrados);
    }//GEN-LAST:event_BtnBuscar1ActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        IConexionBD conexion = new ConexionBD();
        IUsoDAO usoDAO = new UsoDAO(conexion);
        IIpDAO ipDAO = new IpDAO(conexion);
        IEquipoDAO equipoDAO = new EquipoDAO(conexion);
        IAlumnoDAO alumnoDAO = new AlumnoDAO(conexion);
        IUsoNegocio usoNegocio = new UsoNegocio(usoDAO, ipDAO, equipoDAO, alumnoDAO);
        FrmEquipoSeleccion pantalla = new FrmEquipoSeleccion(
                equipoNegocio,
                usoNegocio,
                new AlumnoEntidad(),
                "Cisco"
        );
        pantalla.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnContunuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContunuarActionPerformed
        // TODO add your handling code here:
        try {
            DlgApartadoConfirmacion dlg = new DlgApartadoConfirmacion(
                    (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                    numeroEquipo);

            DlgApartadoConfirmacion.Resultado resultado = dlg.mostrar();

            if (resultado == DlgApartadoConfirmacion.Resultado.OK) {
                equipoNegocio.cambiarEstadoEquipo(idEquipo, "Apartado");
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Equipo " + numeroEquipo + " apartado exitosamente.",
                        "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                IConexionBD conexion = new ConexionBD();
                IAlumnoDAO alumnoDAO = new AlumnoDAO(conexion);
                IEquipoDAO equipoDAO = new EquipoDAO(conexion);
                IAlumnoNegocio alumnoNeg = new AlumnoNegocio(alumnoDAO);
                IEquipoNegocio equipoNeg = new EquipoNegocio(equipoDAO);
                FrmIngresoID frm = new FrmIngresoID(alumnoNeg, equipoNeg);
                frm.setVisible(true);
                this.dispose();
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al apartar equipo: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnContunuarActionPerformed
    private void cargarSoftwares() {
        try {
            todosSoftwares = equipoNegocio.obtenerSoftwaresPorEquipo(idEquipo);
            mostrarSoftwares(todosSoftwares);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar softwares: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarSoftwares(List<SoftwareDTO> softwares) {
        if (softwares == null || softwares.isEmpty()) {
            LblLista.setText("<html><i>No se encontraron softwares.</i></html>");
            return;
        }
        StringBuilder sb = new StringBuilder("<html>");
        for (SoftwareDTO sw : softwares) {
            sb.append("• ").append(sw.getNombre()).append("<br>");
        }
        sb.append("</html>");
        LblLista.setText(sb.toString());
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar1;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContunuar;
    private javax.swing.JLabel LblLista;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JTextField TxtBuacador;
    // End of variables declaration//GEN-END:variables
}
